name: Update Dependencies

on:
  [push]
  # Run every day at midnight UTC
  # schedule:
  #   - cron: "52 * * * *"

jobs:
  update_deps:
    if: github.repository_owner == 'meganesu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "update-deps"
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          cd final/gateway
          npm install
          npm update
          cd ../..
      - run: |
          cd final/subgraph-activities
          npm install
          npm update
          cd ../..
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: updated dependencies"
          git push --set-upstream origin update-deps
      - run: gh pr create --fill
