name: Update Dependencies

env:
  # For using the GitHub CLI:
  GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
    branches:
      - main
  # Run every day at midnight UTC
  # schedule:
  #   - cron: "52 * * * *"

jobs:
  update_deps:
    if: github.repository_owner == 'meganesu'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "update-deps"
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: "npm install"
        run: |
          npm install
          node utils/install.js
          node utils/install-final-dir.js
      - name: "npm update"
        run: node utils/update-deps.js
      - name: "Commit & push changes"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: updated dependencies"
          git push --set-upstream origin update-deps
      - run: gh pr create --fill
